server:
    port: 8080 #启动端口
# SPRING PROFILES
spring:
    # DATASOURCE
    datasource:
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.135:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456


